pipeline {
    agent {
        label 'dotnetcore31'
    }
    stages {
       stage('build') {
          steps {
             echo 'Notify GitLab'
             updateGitlabCommitStatus name: 'build', state: 'pending'
             echo 'build step goes here'
             sh(script: "dotnet build", returnStdout: true)
             updateGitlabCommitStatus name: 'build', state: 'success'
          }
       }
       stage('test') {
           steps {
               echo 'Notify GitLab'
               updateGitlabCommitStatus name: 'test', state: 'pending'
               echo 'test step goes here'
               updateGitlabCommitStatus name: 'test', state: 'success'

           }
       }
    }
 }