pipeline {
    agent any
    environment {
        HOME = '/tmp'
    }

    stages {
       stage('build') {
          steps {
            //  echo 'Notify GitLab'
            //  updateGitlabCommitStatus name: 'build', state: 'pending'
             echo 'build step goes here'
             sh(script: "dotnet build Transcript.API/Transcript.API.csproj -c Release -o ./dist", returnStdout: true)
            //  updateGitlabCommitStatus name: 'build', state: 'success'
          }
       }
       stage('test') {
           steps {
               echo 'Notify GitLab'
            //    updateGitlabCommitStatus name: 'test', state: 'pending'
               echo 'test step goes here'
               sh(script: "dotnet test TranscriptAPI.Tests/Transcript.API.Tests.csproj -c Release -r ./test-results", returnStdout: true)
            //    updateGitlabCommitStatus name: 'test', state: 'success'
           }
       }
    }
 }