apiVersion: v1
kind: Template
metadata:
  name: "${NAME}-build-template"

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: "${NAME}"
      labels:
        app: "${APP_NAME}"

  - kind: BuildConfig
    apiVersion: v1
    metadata:
      name: "${NAME}"
      labels:
        app: "${APP_NAME}"
    spec:
      triggers:
        - type: ImageChange
        - type: ConfigChange
      runPolicy: Serial
      source:
        type: Git
        git:
          uri: "${GIT_REPO_URL}"
          ref: "${GIT_REF}"
        contextDir: "${SOURCE_CONTEXT_DIR}"
        # sourceSecret:
        #   name: ${GIT_SECRET}
      strategy:
        type: Source
        sourceStrategy:
          env:
            - name: DOTNET_STARTUP_PROJECT
              value: Transcript.API
          # - name: DOTNET_TEST_PROJECTS
          #   value: tests/jsg-filing-surrogate-api.tests/jsg-filing-surrogate-api.tests.csproj
          from:
            kind: "${SOURCE_IMAGE_KIND}"
            name: "${SOURCE_IMAGE_NAME}:${SOURCE_IMAGE_TAG}"
            namespace: openshift
      output:
        to:
          kind: ImageStreamTag
          name: "${NAME}:${OUTPUT_IMAGE_TAG}"

  # - kind: BuildConfig
  #   apiVersion: v1
  #   metadata:
  #     name: ${NAME}-pipeline
  #     namespace: ${OPENSHIFT_PROJECT}
  #   spec:
  #     nodeSelector: null
  #     output: {}
  #     postCommit: {}
  #     resources: {}
  #     runPolicy: Serial
  #     source:
  #       contextDir: jenkins
  #       git:
  #         uri: "${GIT_REPO_URL}"
  #       sourceSecret:
  #         name: ${GIT_SECRET}
  #       type: Git
  #     strategy:
  #       jenkinsPipelineStrategy:
  #         jenkinsfilePath: ${JENKINSFILE_PATH}
  #       type: JenkinsPipeline
  #     triggers:
  #       - gitlab:
  #           secretReference:
  #             name: ${GITLAB_WEBHOOK}
  #         type: GitLab

parameters:
  - name: NAME
    displayName: Name
    description: The name assigned to all of the resources defined in this template.
    required: true
  - name: APP_NAME
    displayName: App Name
    description: Used to group components together.
    required: true
  - name: GIT_REPO_URL
    displayName: Git Repo URL
    description: The URL to your GIT repo.
    required: true
  - name: GIT_REF
    displayName: Git Reference
    description: The git reference or branch.
    required: true
  - name: SOURCE_CONTEXT_DIR
    displayName: Source Context Directory
    description: The source context directory.
    required: true
  - name: SOURCE_IMAGE_KIND
    displayName: Source Image Kind
    description: The 'kind' (type) of the  source image; typically ImageStreamTag, or DockerImage.
    required: true
  - name: SOURCE_IMAGE_NAME
    displayName: Source Image Name
    description: The name of the source image.
    required: true
  - name: SOURCE_IMAGE_TAG
    displayName: Source Image Tag
    description: The tag of the source image.
    required: true
  - name: OUTPUT_IMAGE_TAG
    displayName: Output Image Tag
    description: The tag given to the built image.
    required: true
  - name: JENKINSFILE_PATH
    displayName: JENKINSFILE_PATH
    description: The relative path to the JenkinsFile, this path is expected to be found in a folder named jenkins which is at the root of the repo
    required: true
  - name: GITLAB_WEBHOOK
    displayName: GITLAB_WEBHOOK
    description: The name of the webhook used by the pipeline to listen for repo changes
    required: true
  - name: OPENSHIFT_PROJECT
    displayName: OPENSHIFT_PROJECT
    description: The OpenShift tools project name where these objects should be created
    required: true
  - name: GIT_SECRET
    displayName: GIT_SECRET
    description: The name of the OpenShift secret with the repo credentials.
    required: true
